version: '3'
services:
  postgres:
    image: postgres
    container_name: kiraye-az-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
